# Starter pipeline

trigger:
- master

pool:
  vmImage: 'macOS-10.14'


steps:
- task: Gradle@2
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'build'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: false
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      ls -R build/libs/
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'build/libs'
    ArtifactName: 'jar'
    publishLocation: 'Container'